query featuredQuery($shopId: ID!) {
  featuredProductsByShop(shopId: $shopId) {
    nodes {
      _id
      ...on CatalogItemProduct {
        product {
          title
          description
          vendor
          slug
          isLowQuantity
          isSoldOut
          isBackorder
          metafields {
              description
              key
              namespace
              scope
              value
              valueType
            }
            shop {
              currency {
                code
              }
            }
          pricing {
              compareAtPrice {
                displayAmount
              }
              currency {
                code
              }
              displayPrice
              minPrice
              maxPrice
            }
          primaryImage {
              URLs {
                thumbnail
                small
                medium
                large
              }
            }
          media {
            URLs {
              thumbnail
              small
              medium
              large
            }
          }
        }
      }
    }
  }
}
